{
    'name': 'Academy Management',
    'version': '18.0.4.0.0',
    'category': 'Education',
    'summary': 'Academy Management - Day 4 (A) QWeb PDF Report (Certificate)',
    'depends': ['base', 'mail'],
    'data': [
        'security/academy_groups.xml',
        'security/ir.model.access.csv',
        'security/academy_record_rules.xml',
        'data/academy_data.xml',
        'views/academy_course_views.xml',
        'views/academy_student_views.xml',
        'views/academy_batch_views.xml',
        'views/academy_enrollment_views.xml',
        'views/academy_course_inherit_views.xml',
        'views/academy_batch_inherit_views.xml',
        'views/academy_views.xml',
        'wizards/reject_enrollment_wizard_views.xml',
        'reports/academy_enrollment_certificate_report.xml',
        'views/academy_menus.xml',
    ],
    'application': True,
    'license': 'LGPL-3',
}
