{
    'name': 'Academy Management',
    'version': '18.0.5.3.0',
    'category': 'Education',
    'summary': 'Day 5 Checkpoint C - GET Course Detail and 404',
    'depends': ['base', 'mail'],
    'data': [
        'security/academy_groups.xml',
        'security/ir.model.access.csv',
        'security/academy_record_rules.xml',
        'data/academy_data.xml',
        'data/academy_api_data.xml',
        'views/academy_course_views.xml',
        'views/academy_student_views.xml',
        'views/academy_batch_views.xml',
        'views/academy_enrollment_views.xml',
        'views/academy_course_inherit_views.xml',
        'views/academy_batch_inherit_views.xml',
        'views/academy_views.xml',
        'wizards/reject_enrollment_wizard_views.xml',
        'wizards/enrollment_export_wizard_views.xml',
        'wizards/import_external_courses_wizard_views.xml',
        'reports/academy_enrollment_certificate_report.xml',
        'views/academy_menus.xml',
    ],
    'external_dependencies': {'python': ['xlsxwriter', 'requests']},
    'application': True,
    'license': 'LGPL-3',
}
