{
    "name": "Academy Management",
    "version": "18.0.1.0.0",
    "summary": "Academy Management System",
    "category": "Education",
    "depends": ["base", "mail","sale"],
    "data": [
        "security/academy_groups.xml",
        "security/ir.model.access.csv",
        "security/academy_record_rules.xml",
        "data/academy_data.xml",
        "data/ir_sequence_data.xml",
        "data/academy_api_data.xml",
        "views/academy_course_views.xml",
        "views/academy_student_views.xml",
        "views/academy_batch_views.xml",
        "views/academy_enrollment_views.xml",
        # "views/academy_course_inherit_views.xml",
        # "views/academy_batch_inherit_views.xml",
        "wizards/reject_enrollment_wizard_views.xml",
        "wizards/enrollment_export_wizard_views.xml",
        "wizards/import_external_courses_wizard_views.xml",
        "reports/academy_enrollment_certificate_report.xml",
        "reports/sale_order_report_inherit.xml",
        "views/academy_menus.xml",
    ],
    "application": True,
    "license": "LGPL-3",
}
